
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.formatDate(System.Nullable{System.DateTimeOffset},System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.getFieldValue(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.getFieldValueISODate(System.Nullable{System.DateTimeOffset})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidNonRequiredEMail(System.String,System.Int32,System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidNonRequiredString(System.String,System.Int32,System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidRequiredDate(System.Nullable{System.DateTimeOffset},System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidRequiredEMail(System.String,System.Int32,System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidRequiredInt(System.Nullable{System.Int32},System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CommonService.CommonService.isValidRequiredString(System.String,System.Int32,System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Evolution.CommonService.CommonService.dbStatic")]