
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createSalesOrderDetailTemp(Evolution.Models.Models.SalesOrderHeaderTempModel,Evolution.Models.Models.CompanyModel,Evolution.Models.Models.CustomerModel,Evolution.Models.Models.UserModel,System.Int32)~Evolution.Models.Models.SalesOrderDetailTempModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createSalesOrderDetail(Evolution.Models.Models.SalesOrderDetailModel)~Evolution.Models.Models.SalesOrderDetailModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createSalesOrderDetail(System.Collections.Generic.List{Evolution.Models.Models.SalesOrderDetailModel})~Evolution.Models.Models.SalesOrderDetailModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.isEqual(System.Collections.Generic.Dictionary{System.String,System.String},System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.DeleteSalesOrderHeaderTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.getCreditClaimHeader~Evolution.Models.Models.CreditClaimHeaderModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.getCreditClaimHeader~Evolution.Models.Models.CreditClaimHeaderModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.getCreditClaimReplacementOrder(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.CreditClaimHeaderModel,Evolution.Models.Models.SalesOrderHeaderModel)~Evolution.Models.Models.CreditClaimReplacementOrderModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.getCreditClaimReplacementOrder(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.CreditClaimHeaderModel,Evolution.Models.Models.SalesOrderHeaderModel)~Evolution.Models.Models.CreditClaimReplacementOrderModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.CopyTempToSalesOrderHeaderTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.FindSalesOrderHeaderModelFromTempIdTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.FindSalesOrderHeaderModelTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createPicksTest(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createPicksTest(System.Collections.Generic.List{Evolution.Models.Models.SalesOrderHeaderModel},System.Boolean,System.Collections.Generic.List{Evolution.Models.Models.PickHeaderModel})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.createPicksTest(System.Int32,System.Int32,System.Collections.Generic.List{Evolution.Models.Models.SalesOrderHeaderModel},System.Boolean,System.Collections.Generic.List{Evolution.Models.Models.PickHeaderModel})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.SalesServiceTests.SalesServiceTests.FindSalesOrderHeaderTempModelTest")]