
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.createNoteWithAttachment(Evolution.Models.Models.PurchaseOrderHeaderModel,Evolution.Models.Models.CompanyModel,System.String,Evolution.Models.Models.NoteModel,System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.deleteOrArchiveFiles(Evolution.Models.Models.FileTransferConfigurationModel,Evolution.FTPService.FTPService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.findUserGroupForSalesPerson(Evolution.Models.Models.PurchaseOrderHeaderModel,Evolution.Models.Models.CompanyModel,System.Int32,System.Collections.Generic.List{Evolution.Models.Models.UserModel}@,System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.processFiles(Evolution.Models.Models.FileTransferConfigurationModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.sendUnpackSlipMessage(Evolution.Models.Models.PurchaseOrderHeaderModel,Evolution.Models.Models.CompanyModel,Evolution.Models.Models.NoteModel,System.Int32,System.Collections.Generic.List{Evolution.Models.Models.UserModel})~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.NotificationTask.checkForPassedUnpackDates")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.createNoteWithAttachment(Evolution.Models.Models.PurchaseOrderHeaderModel,Evolution.Models.Models.CompanyModel,System.String,Evolution.Models.Models.NoteModel@,System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.sendUnpackSlipMessage(Evolution.Models.Models.PurchaseOrderHeaderModel,Evolution.Models.Models.CompanyModel,Evolution.Models.Models.NoteModel,System.Int32,System.Collections.Generic.List{Evolution.Models.Models.UserModel})~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.DataTransferTask.receiveFiles(Evolution.Models.Models.FileTransferConfigurationModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.DataTransferTask.sendFiles(Evolution.Models.Models.FileTransferConfigurationModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskProcessor.UnpackSlipReceiverTask.deleteOrArchiveFile(Evolution.Models.Models.FileTransferConfigurationModel,Evolution.FTPService.FTPService,System.String)")]