
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createBrandCategoryWithBrands(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32)~Evolution.Models.Models.BrandCategoryModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createBrandWithProducts(Evolution.Models.Models.UserModel)~Evolution.Models.Models.BrandModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createProduct(Evolution.Models.Models.UserModel,Evolution.Models.Models.BrandModel)~Evolution.Models.Models.ProductModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createBrand~Evolution.Models.Models.BrandModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createBrandCategory(Evolution.Models.Models.CompanyModel)~Evolution.Models.Models.BrandCategoryModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createProductLocation(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.ProductModel,Evolution.Models.Models.ProductLocationModel,System.Int32)~Evolution.Models.Models.ProductLocationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createProductLocation(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.ProductModel,Evolution.Models.Models.LocationModel,System.Int32)~Evolution.Models.Models.ProductLocationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createProductCompliance(System.Int32,System.Int32,System.Int32)~Evolution.Models.Models.ProductComplianceModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductServiceTests.ProductServiceTests.createProductCompliance(System.Int32,System.Int32,System.Int32)~Evolution.Models.Models.ProductComplianceModel")]