//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SaleLineId { get; set; }
        public Nullable<int> PurchaseLineId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual SalesOrderDetail SalesOrderDetail { get; set; }
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
    }
}
