//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public System.DateTimeOffset ChangedDate { get; set; }
        public string TableName { get; set; }
        public string BusinessArea { get; set; }
        public int RowId { get; set; }
        public int UserId { get; set; }
        public string FieldName { get; set; }
        public string BeforeValue { get; set; }
        public string AfterValue { get; set; }
    
        public virtual User User { get; set; }
    }
}
