//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandCategorySalesPerson
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int BrandCategoryId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public int SalesPersonTypeId { get; set; }
    
        public virtual BrandCategory BrandCategory { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
