//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountrySubDivision
    {
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string ISOSubDivCode2 { get; set; }
        public string ISOSubDivCode5 { get; set; }
        public string ISOSubDivCode6 { get; set; }
        public string SubDivName { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
