//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditClaimReplacementOrder
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int CreditClaimHeaderId { get; set; }
        public int SalesOrderHeaderId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CreditClaimHeader CreditClaimHeader { get; set; }
        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
    }
}
