//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditClaimHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditClaimHeader()
        {
            this.CreditClaimLines = new HashSet<CreditClaimLine>();
            this.CreditClaimReplacementOrders = new HashSet<CreditClaimReplacementOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
        public Nullable<int> ClaimNumber { get; set; }
        public Nullable<byte> ClaimCategoryID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string NotesAndComments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTimeOffset> ApprovedByDate { get; set; }
        public Nullable<System.DateTimeOffset> DateFinalised { get; set; }
        public Nullable<System.DateTimeOffset> DateCancelled { get; set; }
        public string PickupAddress { get; set; }
        public Nullable<System.DateTimeOffset> DateRejected { get; set; }
        public Nullable<int> RejectionReasonId { get; set; }
        public string RejectionReasonComments { get; set; }
        public Nullable<int> ReturnTypeId { get; set; }
        public Nullable<int> Carrier { get; set; }
        public string ConNote { get; set; }
        public Nullable<System.DateTimeOffset> PickupBookedDate { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedByWarehoseDate { get; set; }
        public Nullable<int> PickupBoxCount { get; set; }
        public Nullable<int> PickupBoxWeightKg { get; set; }
        public string PickupBoxDimensions { get; set; }
        public string PickupSpecialInstructions { get; set; }
        public bool ReplacementRequired { get; set; }
        public Nullable<int> ReplacementOrderId { get; set; }
        public Nullable<int> CustomerContactId { get; set; }
        public string CustomerContactEmail { get; set; }
        public string CustomerContactPhone { get; set; }
        public Nullable<decimal> FreightToCredit { get; set; }
        public string CustomerReference { get; set; }
        public Nullable<int> ReturnToWarehouseId { get; set; }
        public string ReturnAddress { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedByWarehouseDate { get; set; }
        public Nullable<float> FreightCreditPercent { get; set; }
        public Nullable<float> FreightCreditFixedAmount { get; set; }
        public Nullable<int> RaisedById { get; set; }
        public Nullable<int> CreditNoteFreightDescriptionId { get; set; }
        public Nullable<int> ReplacementOrderNo { get; set; }
        public Nullable<int> RejectedById { get; set; }
        public Nullable<int> ReturnAddressId { get; set; }
    
        public virtual CreditClaimReason CreditClaimReason { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual LOVItem LOVItem1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditClaimLine> CreditClaimLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditClaimReplacementOrder> CreditClaimReplacementOrders { get; set; }
    }
}
