//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditClaimLine
    {
        public int Id { get; set; }
        public Nullable<int> CreditClaimId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OriginalSaleLineId { get; set; }
        public Nullable<int> OriginalQty { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> OriginalDiscount { get; set; }
        public Nullable<int> CreditQty { get; set; }
        public Nullable<decimal> CreditPrice { get; set; }
        public Nullable<decimal> CreditDiscount { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<int> ItemConditionId { get; set; }
        public string AdditionalNotes { get; set; }
        public bool InvoicedItem { get; set; }
        public Nullable<int> SeverityId { get; set; }
        public bool IsReturnedToStock { get; set; }
    
        public virtual CreditClaimHeader CreditClaimHeader { get; set; }
        public virtual CreditClaimItemCondition CreditClaimItemCondition { get; set; }
        public virtual CreditClaimReason CreditClaimReason { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual Product Product { get; set; }
    }
}
