//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currency()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Sales = new HashSet<Sale>();
            this.ShipmentContents = new HashSet<ShipmentContent>();
            this.ShipmentContents1 = new HashSet<ShipmentContent>();
            this.ShipmentContents2 = new HashSet<ShipmentContent>();
            this.ShipmentContents3 = new HashSet<ShipmentContent>();
            this.SupplierPayments = new HashSet<SupplierPayment>();
            this.OrderPayments = new HashSet<OrderPayment>();
            this.Companies = new HashSet<Company>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            this.PurchaseOrderHeaderTemps = new HashSet<PurchaseOrderHeaderTemp>();
            this.CustomerDefaults = new HashSet<CustomerDefault>();
        }
    
        public int Id { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string CurrencySymbol { get; set; }
        public string FormatTemplate { get; set; }
        public Nullable<int> LinkedReceivablesAccountID { get; set; }
        public Nullable<int> LinkedReceivablesFreightID { get; set; }
        public Nullable<int> LinkedReceivablesDepositsID { get; set; }
        public Nullable<int> LinkedReceivablesDiscountsID { get; set; }
        public Nullable<int> LinkedReceivablesLateFeesID { get; set; }
        public Nullable<int> LinkedPayablesAccountID { get; set; }
        public Nullable<int> LinkedReceivablesChequeID { get; set; }
        public Nullable<int> LinkedPayablesChequeID { get; set; }
        public Nullable<int> LinkedPayablesInventoryID { get; set; }
        public Nullable<int> LinkedPayablesFreightID { get; set; }
        public Nullable<int> LinkedPayablesDepositsID { get; set; }
        public Nullable<int> LinkedPayablesDiscountsID { get; set; }
        public Nullable<int> LinkedPayablesLateFeesID { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentContent> ShipmentContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentContent> ShipmentContents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentContent> ShipmentContents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentContent> ShipmentContents3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPayment> SupplierPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderHeaderTemp> PurchaseOrderHeaderTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDefault> CustomerDefaults { get; set; }
    }
}
