//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.BrandCategorySalesPersons = new HashSet<BrandCategorySalesPerson>();
            this.CreditCards = new HashSet<CreditCard>();
            this.CreditClaimHeaders = new HashSet<CreditClaimHeader>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerConflictSensitivities = new HashSet<CustomerConflictSensitivity>();
            this.CustomerConflictSensitivities1 = new HashSet<CustomerConflictSensitivity>();
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.MarketingGroupSubscriptions = new HashSet<MarketingGroupSubscription>();
            this.PickHeaders = new HashSet<PickHeader>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesOrderDetailTemps = new HashSet<SalesOrderDetailTemp>();
            this.FileImportRows = new HashSet<FileImportRow>();
            this.SalesOrderHeaderTemps = new HashSet<SalesOrderHeaderTemp>();
            this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
            this.Tasks = new HashSet<Task>();
            this.NuOrderImportTemps = new HashSet<NuOrderImportTemp>();
            this.ShopifyImportHeaderTemps = new HashSet<ShopifyImportHeaderTemp>();
        }
    
        public int Id { get; set; }
        public int OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public int CardRecordId { get; set; }
        public string Name { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> PotentialId { get; set; }
        public Nullable<int> MiscGroupingId { get; set; }
        public int PaymentTermId { get; set; }
        public int PriceLevelId { get; set; }
        public int TaxCodeId { get; set; }
        public Nullable<int> FreightTaxCodeId { get; set; }
        public bool UseCustomerTaxCode { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> VolumeDiscount { get; set; }
        public Nullable<int> ShippingTemplateId { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public bool OnHold { get; set; }
        public string ShipMethodAccount { get; set; }
        public Nullable<bool> IsManualFreight { get; set; }
        public Nullable<decimal> FreightRate { get; set; }
        public Nullable<decimal> MinFreightPerOrder { get; set; }
        public Nullable<int> FreightCarrierId { get; set; }
        public string DeliveryInstructions { get; set; }
        public string DeliveryContact { get; set; }
        public bool SendInvoices { get; set; }
        public bool EmailAcctMgrOnSaleChange { get; set; }
        public bool EmailAcctMgrOnLinkedPurchaseChange { get; set; }
        public bool RequireAuthorisation4OrderQtyChange { get; set; }
        public bool AllowSalesInNonMSQMultiples { get; set; }
        public string ProductLabelName { get; set; }
        public bool SendPOSFile { get; set; }
        public bool RemoveCustNameFromAddressWhenDrop { get; set; }
        public bool ExcludeFromSalesGraphs { get; set; }
        public Nullable<decimal> MinFreightThreshold { get; set; }
        public Nullable<decimal> FreightWhenBelowThreshold { get; set; }
        public string WarehouseInstructions { get; set; }
        public Nullable<int> FreightTermId { get; set; }
        public Nullable<int> UnassignedRetailInvoiceNumber { get; set; }
        public string TaxId { get; set; }
        public string EDI_VendorNo { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string PricingInstructions { get; set; }
        public bool SyncToMYOB { get; set; }
        public bool InMYOB { get; set; }
        public bool PlacesForwardOrders { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string OurVendorId { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<double> OpenOrders { get; set; }
        public bool IsOverdue { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCategorySalesPerson> BrandCategorySalesPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditClaimHeader> CreditClaimHeaders { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual LOVItem LOVItem1 { get; set; }
        public virtual LOVItem LOVItem2 { get; set; }
        public virtual LOVItem LOVItem3 { get; set; }
        public virtual LOVItem LOVItem4 { get; set; }
        public virtual LOVItem LOVItem5 { get; set; }
        public virtual LOVItem LOVItem6 { get; set; }
        public virtual PriceLevel PriceLevel { get; set; }
        public virtual Region Region { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual TaxCode TaxCode1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerConflictSensitivity> CustomerConflictSensitivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerConflictSensitivity> CustomerConflictSensitivities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketingGroupSubscription> MarketingGroupSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickHeader> PickHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetailTemp> SalesOrderDetailTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileImportRow> FileImportRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderHeaderTemp> SalesOrderHeaderTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuOrderImportTemp> NuOrderImportTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopifyImportHeaderTemp> ShopifyImportHeaderTemps { get; set; }
        public virtual MessageTemplate MessageTemplate { get; set; }
    }
}
