//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsDelay
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> PortArrivalId { get; set; }
        public Nullable<int> ShipMethodId { get; set; }
        public Nullable<int> ContainerTypeId { get; set; }
        public Nullable<int> CustomsDelayDays { get; set; }
        public bool Enabled { get; set; }
    
        public virtual LOVItem LOVItem { get; set; }
        public virtual Port Port { get; set; }
        public virtual Company Company { get; set; }
    }
}
