//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int AddressTypeId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string StreetLine3 { get; set; }
        public string StreetLine4 { get; set; }
        public Nullable<System.DateTimeOffset> DateStart { get; set; }
        public Nullable<System.DateTimeOffset> DateEnd { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LOVItem LOVItem_AddressType { get; set; }
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
    }
}
