//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryWindow
    {
        public int Id { get; set; }
        public int MMDDStart { get; set; }
        public int MMDDEnd { get; set; }
        public string OffsetBase { get; set; }
        public string OffsetType { get; set; }
        public int OffsetValue { get; set; }
    }
}
