//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMailQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMailQueue()
        {
            this.EMailQueueAttachments = new HashSet<EMailQueueAttachment>();
        }
    
        public int Id { get; set; }
        public System.DateTimeOffset QueuedDate { get; set; }
        public string SenderAddress { get; set; }
        public string ReplyToAddress { get; set; }
        public string RecipientAddress { get; set; }
        public string CopyAddress { get; set; }
        public string BCCAddress { get; set; }
        public string MessageSubject { get; set; }
        public string MessageText { get; set; }
        public int Retries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMailQueueAttachment> EMailQueueAttachments { get; set; }
    }
}
