//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTransferConfiguration
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int TransferType { get; set; }
        public int DataTypeId { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string TransferName { get; set; }
        public string FTPHost { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public int Protocol { get; set; }
        public string SourceFolder { get; set; }
        public string TargetFolder { get; set; }
        public string ArchiveFolder { get; set; }
        public string ErrorFolder { get; set; }
        public string ConfigurationTemplate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> FreightForwarderId { get; set; }
        public string PostTransferCommand { get; set; }
        public string PostTransferParameters { get; set; }
        public string TargetFileNameFormat { get; set; }
        public bool Enabled { get; set; }
    
        public virtual FreightForwarder FreightForwarder { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
        public virtual LOVItem LOVItem_DataType { get; set; }
    }
}
