//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingGroupSubscription
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int CustomerId { get; set; }
        public int CustomerContactId { get; set; }
        public int MarketingGroupId { get; set; }
        public Nullable<System.DateTimeOffset> DateFrom { get; set; }
        public Nullable<System.DateTimeOffset> DateTo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual MarketingGroup MarketingGroup { get; set; }
        public virtual Company Company { get; set; }
    }
}
