//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingGroup()
        {
            this.MarketingGroupSubscriptions = new HashSet<MarketingGroupSubscription>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public string MarketingGroupName { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketingGroupSubscription> MarketingGroupSubscriptions { get; set; }
        public virtual Company Company { get; set; }
    }
}
