//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetadataElement()
        {
            this.MetadataTemplateElements = new HashSet<MetadataTemplateElement>();
        }
    
        public int Id { get; set; }
        public string ElementName { get; set; }
        public string DisplayLabel { get; set; }
        public int DataTypeId { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public int MaxLength { get; set; }
        public Nullable<int> LovId { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public bool Required { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetadataTemplateElement> MetadataTemplateElements { get; set; }
    }
}
