//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataTemplateElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetadataTemplateElement()
        {
            this.ProductDatas = new HashSet<ProductData>();
        }
    
        public int Id { get; set; }
        public int MetadataTemplateId { get; set; }
        public int MetadataElementId { get; set; }
        public int OrderNo { get; set; }
    
        public virtual MetadataElement MetadataElement { get; set; }
        public virtual MetadataTemplate MetadataTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductData> ProductDatas { get; set; }
    }
}
