//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.NoteAttachments = new HashSet<NoteAttachment>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int NoteType { get; set; }
        public int ParentId { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public int CreatedById { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteAttachment> NoteAttachments { get; set; }
    }
}
