//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuOrderImportTemp
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int SourceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string CustomerPO { get; set; }
        public Nullable<System.DateTimeOffset> OrderDate { get; set; }
        public Nullable<System.DateTimeOffset> RequiredDate { get; set; }
        public string CompanyName { get; set; }
        public string EndUserName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipAddress4 { get; set; }
        public string ShipSuburb { get; set; }
        public string ShipState { get; set; }
        public string ShipPostcode { get; set; }
        public Nullable<int> ShipCountryId { get; set; }
        public Nullable<int> SOStatus { get; set; }
        public Nullable<int> SOSubstatus { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public string OrderComment { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public string WebsiteOrderNo { get; set; }
        public string Filespec { get; set; }
        public string Telephone { get; set; }
        public string EmailAddress { get; set; }
        public string Comments { get; set; }
        public bool IsError { get; set; }
        public Nullable<System.DateTimeOffset> DeliveryWindowOpen { get; set; }
        public Nullable<System.DateTimeOffset> DeliveryWindowClose { get; set; }
        public Nullable<bool> ManualDWO { get; set; }
        public Nullable<bool> ManualDWC { get; set; }
        public string ShippingMethodAccount { get; set; }
        public Nullable<int> NextActionId { get; set; }
        public bool IsConfirmedAddress { get; set; }
        public bool IsManualFreight { get; set; }
        public Nullable<decimal> FreightRate { get; set; }
        public Nullable<decimal> MinFreightPerOrder { get; set; }
        public Nullable<int> FreightCarrierId { get; set; }
        public string DeliveryInstructions { get; set; }
        public string DeliveryContact { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTimeOffset> DateSigned { get; set; }
        public Nullable<int> MethodSignedId { get; set; }
        public Nullable<int> PrintedForm { get; set; }
        public string WarehouseInstructions { get; set; }
        public bool IsMSQProblem { get; set; }
        public bool IsOverrideMSQ { get; set; }
        public Nullable<int> FreightTermId { get; set; }
        public string SiteName { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<bool> IsRetailSale { get; set; }
        public Nullable<bool> IsRetailHoldingOrder { get; set; }
        public Nullable<int> BrandCategoryId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> UnitPriceExTax { get; set; }
        public Nullable<decimal> UnitPriceTax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<int> AllocQty { get; set; }
        public Nullable<int> PickQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> LineStatusId { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
        public Nullable<System.DateTimeOffset> DateModified { get; set; }
    
        public virtual BrandCategory BrandCategory { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual FreightCarrier FreightCarrier { get; set; }
        public virtual Location Location { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual MethodSigned MethodSigned { get; set; }
        public virtual SalesOrderHeaderStatu SalesOrderHeaderStatu { get; set; }
        public virtual SalesOrderHeaderSubStatu SalesOrderHeaderSubStatu { get; set; }
        public virtual SalesOrderLineStatu SalesOrderLineStatu { get; set; }
        public virtual TaxCode TaxCode { get; set; }
    }
}
