//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public int OrderNo { get; set; }
        public System.DateTimeOffset PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public bool IsDeposit { get; set; }
        public bool IsSchedule { get; set; }
        public bool IsChasing { get; set; }
        public bool IsDelayed { get; set; }
        public string Comment { get; set; }
        public int SupplierPaymentLineId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Company Company { get; set; }
    }
}
