//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickHeader()
        {
            this.PickDetails = new HashSet<PickDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTimeOffset> PickDate { get; set; }
        public Nullable<int> PickStatusId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTimeOffset> STWDate { get; set; }
        public Nullable<System.DateTimeOffset> PickComplete { get; set; }
        public Nullable<System.DateTimeOffset> PackComplete { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipAddress4 { get; set; }
        public string ShipSuburb { get; set; }
        public string ShipState { get; set; }
        public string ShipPostcode { get; set; }
        public Nullable<System.DateTimeOffset> InvoiceDate { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public bool InvoiceFinalised { get; set; }
        public Nullable<int> ShipMethodId { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<System.DateTimeOffset> ShipDate { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> BoxCount { get; set; }
        public Nullable<int> PickPriority { get; set; }
        public Nullable<int> PickedById { get; set; }
        public Nullable<int> PackedById { get; set; }
        public Nullable<System.DateTimeOffset> ReadyForShippingDate { get; set; }
        public Nullable<int> ShippingDocumentId { get; set; }
        public Nullable<System.DateTimeOffset> AddedToShipManifestDate { get; set; }
        public bool DocumentPrinted { get; set; }
        public string CustPO { get; set; }
        public string SecretComment { get; set; }
        public string PickComment { get; set; }
        public string ShipMethodAccount { get; set; }
        public Nullable<double> FreightCost { get; set; }
        public string DeliveryInstructions { get; set; }
        public string CustomerContact { get; set; }
        public bool IsManualFreight { get; set; }
        public Nullable<int> ShipCountryId { get; set; }
        public Nullable<decimal> OurFreightCost { get; set; }
        public string EnteredBy { get; set; }
        public string WarehouseInstructions { get; set; }
        public string EndUserName { get; set; }
        public Nullable<int> CreditCardId { get; set; }
        public bool IsRetailPick { get; set; }
        public bool IsUploadedToWarehouse { get; set; }
        public Nullable<int> TermsID { get; set; }
        public string UnregisteredFreightCarrier { get; set; }
        public Nullable<System.DateTimeOffset> DateCreditCardCharged { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual LOVItem LOVItem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickDetail> PickDetails { get; set; }
        public virtual PickHeaderStatu PickHeaderStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Company Company { get; set; }
    }
}
