//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int MetadataTemplateElementId { get; set; }
        public string ValueText { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public Nullable<decimal> ValueDec { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
    
        public virtual MetadataTemplateElement MetadataTemplateElement { get; set; }
        public virtual Product Product { get; set; }
    }
}
