//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public short QuantityBreak { get; set; }
        public double QuantityBreakAmount { get; set; }
        public string PriceLevel { get; set; }
        public string PriceLevelNameId { get; set; }
        public double SellingPrice { get; set; }
        public bool PriceIsInclusive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
