//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdditionalCategory
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FormatId { get; set; }
        public Nullable<int> FormatTypeId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> PackingTypeId { get; set; }
        public Nullable<int> AgeGroupId { get; set; }
        public Nullable<int> DvlptTypeId { get; set; }
        public Nullable<int> PCProductId { get; set; }
        public Nullable<int> PCDvlptId { get; set; }
        public Nullable<int> KidsAdultsId { get; set; }
    
        public virtual LOVItem LOVItem_AgeGroup { get; set; }
        public virtual LOVItem LOVItem_Category { get; set; }
        public virtual LOVItem LOVItem_DvlptType { get; set; }
        public virtual LOVItem LOVItem_Format { get; set; }
        public virtual LOVItem LOVItem_FormatType { get; set; }
        public virtual LOVItem LOVItem_PackingType { get; set; }
        public virtual LOVItem LOVItem_PCDvlpt { get; set; }
        public virtual LOVItem LOVItem_PCProduct { get; set; }
        public virtual LOVItem LOVItem_Season { get; set; }
        public virtual Product Product { get; set; }
        public virtual LOVItem LOVItem_KidsAdults { get; set; }
    }
}
