//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComplianceAttachment
    {
        public int Id { get; set; }
        public int ProductComplianceId { get; set; }
        public int MediaId { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual ProductCompliance ProductCompliance { get; set; }
    }
}
