//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Allocations = new HashSet<Allocation>();
            this.CreditClaimLines = new HashSet<CreditClaimLine>();
            this.FileImportRows = new HashSet<FileImportRow>();
            this.PickDetails = new HashSet<PickDetail>();
            this.ProductDatas = new HashSet<ProductData>();
            this.ProductLocations = new HashSet<ProductLocation>();
            this.ProductMedias = new HashSet<ProductMedia>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseOrderDetailTemps = new HashSet<PurchaseOrderDetailTemp>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesOrderDetailTemps = new HashSet<SalesOrderDetailTemp>();
            this.ProductIPs = new HashSet<ProductIP>();
            this.ProductCompliances = new HashSet<ProductCompliance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTimeOffset> ApprovedDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public string ItemName { get; set; }
        public string ItemNameLong { get; set; }
        public string ItemNameFormat { get; set; }
        public string ItemNameStyle { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> AB { get; set; }
        public string Set { get; set; }
        public Nullable<double> QuantityOnHand { get; set; }
        public Nullable<double> ValueOnHand { get; set; }
        public Nullable<double> SellOnOrder { get; set; }
        public Nullable<double> PurchaseOnOrder { get; set; }
        public Nullable<bool> ItemIsSold { get; set; }
        public Nullable<bool> ItemIsBought { get; set; }
        public Nullable<bool> ItemIsInventoried { get; set; }
        public Nullable<int> InventoryAccountId { get; set; }
        public Nullable<int> IncomeAccountId { get; set; }
        public Nullable<int> ExpenseAccountId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<bool> UseDescription { get; set; }
        public string BarCode { get; set; }
        public string InnerBarCode { get; set; }
        public string MasterBarCode { get; set; }
        public Nullable<int> HSCode { get; set; }
        public Nullable<double> UnitCBM { get; set; }
        public Nullable<int> MinSaleQty { get; set; }
        public Nullable<int> MinOrderQty1 { get; set; }
        public Nullable<int> MinOrderQty2 { get; set; }
        public Nullable<double> BaseSellingPrice { get; set; }
        public Nullable<bool> PriceIsInclusive { get; set; }
        public Nullable<int> SellTaxCodeId { get; set; }
        public string SalesTaxCalcBasisId { get; set; }
        public string SellUnitMeasure { get; set; }
        public Nullable<short> SellUnitQuantity { get; set; }
        public Nullable<double> TaxInclusiveLastPurchasePrice { get; set; }
        public Nullable<double> TaxExclusiveLastPurchasePrice { get; set; }
        public Nullable<int> BuyTaxCodeId { get; set; }
        public string BuyUnitMeasure { get; set; }
        public Nullable<short> BuyUnitQuantity { get; set; }
        public Nullable<int> PrimarySupplierId { get; set; }
        public string SupplierItemNumber { get; set; }
        public string SupplierItemName { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<double> MinLevelBeforeReorder { get; set; }
        public Nullable<double> DefaultReorderQuantity { get; set; }
        public Nullable<int> DefaultSellLocationId { get; set; }
        public Nullable<int> DefaultReceiveLocationId { get; set; }
        public Nullable<double> TaxInclusiveStandardCost { get; set; }
        public Nullable<double> TaxExclusiveStandardCost { get; set; }
        public Nullable<double> ReceivedOnOrder { get; set; }
        public Nullable<double> QuantityAvailable { get; set; }
        public Nullable<double> LastUnitPrice { get; set; }
        public Nullable<double> NegativeQuantityOnHand { get; set; }
        public string NegativeValueOnHand { get; set; }
        public Nullable<double> NegativeAverageCost { get; set; }
        public Nullable<double> PositiveAverageCost { get; set; }
        public Nullable<int> ProductStatus { get; set; }
        public Nullable<int> PrimaryMediaId { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> PackedLength { get; set; }
        public Nullable<double> PackedWidth { get; set; }
        public Nullable<double> PackedHeight { get; set; }
        public Nullable<double> PackedWeight { get; set; }
        public Nullable<double> InnerLength { get; set; }
        public Nullable<double> InnerWidth { get; set; }
        public Nullable<double> InnerHeight { get; set; }
        public Nullable<double> InnerWeight { get; set; }
        public Nullable<double> MasterLength { get; set; }
        public Nullable<double> MasterWidth { get; set; }
        public Nullable<double> MasterHeight { get; set; }
        public Nullable<double> MasterWeight { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> CountryOfOriginId { get; set; }
        public Nullable<int> InnerQuantity { get; set; }
        public Nullable<int> OuterQuantity { get; set; }
        public Nullable<int> MasterQuantity { get; set; }
        public Nullable<int> PackingTypeId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> WebCategoryId { get; set; }
        public Nullable<int> WebSubCategoryId { get; set; }
        public Nullable<double> WeightPerProduct { get; set; }
        public Nullable<int> ProductAvailabilityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditClaimLine> CreditClaimLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileImportRow> FileImportRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickDetail> PickDetails { get; set; }
        public virtual ProductMedia ProductMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductData> ProductDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLocation> ProductLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMedia> ProductMedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetailTemp> PurchaseOrderDetailTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetailTemp> SalesOrderDetailTemps { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Country Country { get; set; }
        public virtual LOVItem LOVItem_Manufacturer { get; set; }
        public virtual User User_ApprovalBy { get; set; }
        public virtual User User_CreatedBy { get; set; }
        public virtual LOVItem LOVItem_AB { get; set; }
        public virtual LOVItem LOVItem_PackPackingType { get; set; }
        public virtual ProductAdditionalCategory ProductAdditionalCategory { get; set; }
        public virtual LOVItem LOVItem_Material { get; set; }
        public virtual LOVItem LOVItem_WebCategory { get; set; }
        public virtual LOVItem LOVItem_WebSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductIP> ProductIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCompliance> ProductCompliances { get; set; }
        public virtual LOVItem LOVItem_ProductAvailability { get; set; }
    }
}
