//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDetail()
        {
            this.Allocations = new HashSet<Allocation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public int PurchaseOrderHeaderId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> UnitPriceExTax { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> OrderQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual Company Company { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
        public virtual Product Product { get; set; }
    }
}
