//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetailTemp
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int PurchaseOrderHeaderTempId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> UnitPriceExTax { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> OrderQty { get; set; }
    
        public virtual TaxCode TaxCode { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
        public virtual PurchaseOrderHeaderTemp PurchaseOrderHeaderTemp { get; set; }
        public virtual Product Product { get; set; }
    }
}
