//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> CardRecordId { get; set; }
        public string PurchaseNumber { get; set; }
        public string SupplierInvoiceNumber { get; set; }
        public Nullable<System.DateTimeOffset> Date { get; set; }
        public Nullable<System.DateTimeOffset> PurchaseDate { get; set; }
        public Nullable<bool> IsThirteenthPeriod { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddressLine1 { get; set; }
        public string ShipToAddressLine2 { get; set; }
        public string ShipToAddressLine3 { get; set; }
        public string ShipToAddressLine4 { get; set; }
        public string ShipToAddressLine5 { get; set; }
        public string ShipToAddressLine6 { get; set; }
        public Nullable<double> TotalTax { get; set; }
        public string PurchaseTypeId { get; set; }
        public string PurchaseStatusId { get; set; }
        public string OrderStatusId { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<int> TotalLines { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<double> TotalDeposits { get; set; }
        public Nullable<double> TotalDebits { get; set; }
        public Nullable<double> TotalDiscounts { get; set; }
        public Nullable<double> OutstandingBalance { get; set; }
        public string Memo { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTimeOffset> PromisedDate { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<int> DaysTillPaid { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> TransactionExchangeRate { get; set; }
        public string InvoiceDeliveryId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Company Company { get; set; }
    }
}
