//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public Nullable<int> CardRecordId { get; set; }
        public string InvoiceNumber { get; set; }
        public string CustomerPONumber { get; set; }
        public Nullable<System.DateTimeOffset> Date { get; set; }
        public Nullable<System.DateTimeOffset> InvoiceDate { get; set; }
        public bool IsThirteenthPeriod { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddressLine1 { get; set; }
        public string ShipToAddressLine2 { get; set; }
        public string ShipToAddressLine3 { get; set; }
        public string ShipToAddressLine4 { get; set; }
        public string ShipToAddressLine5 { get; set; }
        public string ShipToAddressLine6 { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public Nullable<double> TaxExclusiveFreight { get; set; }
        public Nullable<double> TaxInclusiveFreight { get; set; }
        public Nullable<int> FreightTaxCodeId { get; set; }
        public Nullable<double> TotalTax { get; set; }
        public string InvoiceTypeId { get; set; }
        public string InvoiceStatusId { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<double> TotalLines { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<double> TotalDeposits { get; set; }
        public Nullable<double> TotalCredits { get; set; }
        public Nullable<double> TotalDiscounts { get; set; }
        public Nullable<double> OutstandingBalance { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public string Memo { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTimeOffset> PromisedDate { get; set; }
        public bool IsTaxInclusive { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<short> DaysTillPaid { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> TransactionExchangeRate { get; set; }
        public string InvoiceDeliveryId { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
