//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetailTemp
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public int SalesOrderHeaderTempId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> UnitPriceExTax { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<int> AllocQty { get; set; }
        public Nullable<int> PickQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> LineStatusId { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
        public Nullable<System.DateTimeOffset> DateModified { get; set; }
        public bool ConflictFlag { get; set; }
        public Nullable<int> ConflictCustomerId { get; set; }
        public bool ConflictApproved { get; set; }
        public Nullable<int> ApprovedBy1Id { get; set; }
        public Nullable<int> ApprovedBy2Id { get; set; }
        public Nullable<System.DateTimeOffset> ApprovedByDate { get; set; }
        public bool ReallocateItem { get; set; }
        public Nullable<decimal> UnitPriceGST { get; set; }
        public string WebsiteLineItemId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual SalesOrderLineStatu SalesOrderLineStatu { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual SalesOrderHeaderTemp SalesOrderHeaderTemp { get; set; }
        public virtual Product Product { get; set; }
    }
}
