//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTaskLog
    {
        public int Id { get; set; }
        public int ScheduledTaskId { get; set; }
        public int Severity { get; set; }
        public System.DateTimeOffset LogDate { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
    
        public virtual ScheduledTask ScheduledTask { get; set; }
    }
}
