//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentPhaseTime
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ShipMethodId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool IsFirstOrder { get; set; }
        public Nullable<int> SRD_CD { get; set; }
        public Nullable<int> Factory_PortDepart { get; set; }
        public Nullable<int> PortArrival_Warehouse { get; set; }
        public Nullable<int> RETA_AdvETA { get; set; }
        public bool UsePortArrival_Warehouse_ForBufferB { get; set; }
        public Nullable<int> ContainerTypeId { get; set; }
    
        public virtual ContainerType ContainerType { get; set; }
        public virtual Location Location { get; set; }
        public virtual LOVItem LOVItem { get; set; }
    }
}
