//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentContent
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> PurchaseOrderHeaderId { get; set; }
        public Nullable<double> CBMEstimate { get; set; }
        public Nullable<double> CBMCharged { get; set; }
        public Nullable<System.DateTimeOffset> DateDepartSupplier { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string ProductBrand { get; set; }
        public Nullable<double> PurchaseValue { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<float> CostedExchangeRate { get; set; }
        public Nullable<System.DateTimeOffset> DatePOSentToSupplier { get; set; }
        public Nullable<System.DateTimeOffset> DateOrderConfirmed { get; set; }
        public string OrderConfirmationNo { get; set; }
        public Nullable<double> EstCBMRate { get; set; }
        public Nullable<double> EstDutyRate { get; set; }
        public Nullable<double> TotalLandedPrice { get; set; }
        public string MainShipInvNo { get; set; }
        public Nullable<System.DateTimeOffset> MainShipInvDate { get; set; }
        public Nullable<double> MainShipAmountLocalEx { get; set; }
        public Nullable<int> MainShipCurrencyId { get; set; }
        public Nullable<double> MainShipExchangeRate { get; set; }
        public Nullable<double> MainShipAUDAmountEx { get; set; }
        public Nullable<double> MainShipGST { get; set; }
        public string OSChargesInvNo { get; set; }
        public Nullable<System.DateTimeOffset> OSChargesInvDate { get; set; }
        public Nullable<double> OSChargesAmountLocalEx { get; set; }
        public Nullable<int> OSChargesCurrencyId { get; set; }
        public Nullable<double> OSChargesExchangeRate { get; set; }
        public Nullable<double> OSChargesAUDAmountEx { get; set; }
        public Nullable<double> OSChargesGSTAmount { get; set; }
        public string LocalHandInvNo { get; set; }
        public Nullable<System.DateTimeOffset> LocalHandInvDate { get; set; }
        public Nullable<double> LocalHandAUDAmountEx { get; set; }
        public Nullable<double> LocalHandGSTAmount { get; set; }
        public string LocalShipInvNo { get; set; }
        public Nullable<System.DateTimeOffset> LocalShipInvDate { get; set; }
        public Nullable<double> LocalShipAUDAmountEx { get; set; }
        public Nullable<double> LocalShipGSTAmount { get; set; }
        public string OtherShipInvNo { get; set; }
        public Nullable<System.DateTimeOffset> OtherShipInvDate { get; set; }
        public Nullable<double> OtherShipAmountLocalEx { get; set; }
        public Nullable<int> OtherShipCurrencyId { get; set; }
        public Nullable<double> OtherShipExchangeRate { get; set; }
        public Nullable<double> OtherShipGSTAmount { get; set; }
        public Nullable<double> OtherShipAUDAmountEx { get; set; }
        public string MainGSTDutyInvNo { get; set; }
        public Nullable<System.DateTimeOffset> MainGSTDutyInvDate { get; set; }
        public Nullable<double> MainGSTDutyNoDutyNoGSTAmount { get; set; }
        public Nullable<double> MainGSTDutyDutyAmount { get; set; }
        public Nullable<double> MainGSTDutyGSTAmount { get; set; }
        public Nullable<double> SupplierFreightLocalAmountEx { get; set; }
        public Nullable<int> SupplierFreightCurrencyID { get; set; }
        public Nullable<double> SupplierFreightAUDAmountEx { get; set; }
        public Nullable<double> ProdDevLocalAmountEx { get; set; }
        public Nullable<int> ProdDevLocalCurrencyId { get; set; }
        public Nullable<double> ProdDevAUDAmountEx { get; set; }
        public string PortToWarehouseInvNo { get; set; }
        public Nullable<double> PortToWarehouseAUDAmountEx { get; set; }
        public Nullable<double> LandingFreightActualAmount { get; set; }
        public Nullable<double> LandingDutyActualAmount { get; set; }
        public Nullable<double> LCSMYOBRate { get; set; }
        public Nullable<double> LCSMYOBRateTotal { get; set; }
        public Nullable<double> LCSMYOBDuty { get; set; }
        public Nullable<double> LCSMYOBDutyTotal { get; set; }
        public Nullable<double> UnspreadLCDiscrepancy { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public Nullable<System.DateTimeOffset> SupplierInvoiceDate { get; set; }
        public Nullable<decimal> PackageWeight { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        public virtual Currency Currency3 { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual Company Company { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
