//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopifyImportDetailTemp
    {
        public int Id { get; set; }
        public Nullable<int> ShopifyImportHeaderTempId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public Nullable<int> LineStatusId { get; set; }
        public string WebsiteLineItemId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductNumber { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<decimal> UnitPriceExTax { get; set; }
        public Nullable<decimal> UnitPriceTax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<int> AllocQty { get; set; }
        public Nullable<int> PickQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
        public Nullable<System.DateTimeOffset> DateModified { get; set; }
        public Nullable<bool> ReallocationItem { get; set; }
    
        public virtual SalesOrderLineStatu SalesOrderLineStatu { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual ShopifyImportHeaderTemp ShopifyImportHeaderTemp { get; set; }
    }
}
