//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int Id { get; set; }
        public Nullable<int> OriginalRowId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierPaymentNumber { get; set; }
        public Nullable<System.DateTimeOffset> Date { get; set; }
        public Nullable<System.DateTimeOffset> TransactionDate { get; set; }
        public string IsThirteenthPeriod { get; set; }
        public string Memo { get; set; }
        public bool IsTaxInclusive { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> TransactionExchangeRate { get; set; }
        public Nullable<int> IssuingAccountId { get; set; }
        public string Payee { get; set; }
        public Nullable<double> TotalSupplierPayment { get; set; }
        public Nullable<double> FinanceCharge { get; set; }
        public Nullable<double> ExchangeGainLoss { get; set; }
        public string IsPrinted { get; set; }
        public string StatementText { get; set; }
        public string PaymentStatusId { get; set; }
        public string PayeeLine1 { get; set; }
        public string PayeeLine2 { get; set; }
        public string PayeeLine3 { get; set; }
        public string PayeeLine4 { get; set; }
        public string PaymentDeliveryId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Company Company { get; set; }
    }
}
