//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolution.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupPermission
    {
        public int Id { get; set; }
        public int UserGroupid { get; set; }
        public int PermissionId { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
