
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.createPurchaseOrderDataFile(Evolution.DAL.PurchaseOrderHeader,System.Xml.Linq.XElement,System.String@)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.doReplacements(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getFileTransferConfiguration(Evolution.DAL.PurchaseOrderHeader,System.String)~Evolution.DAL.FileTransferConfiguration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPurchaseOrder(Evolution.DAL.PurchaseOrderHeader,Evolution.DAL.FileTransferConfiguration,System.String)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getTemplateFileName(Evolution.DAL.FileTransferConfiguration)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.moveFileToFTPFolder(System.String,System.String,System.String)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.createPurchaseOrderDataFile(Evolution.DAL.PurchaseOrderHeader,System.Xml.Linq.XElement,System.String@)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPurchaseOrder(Evolution.DAL.PurchaseOrderHeader,Evolution.DAL.FileTransferConfiguration,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getFileTransferConfiguration(Evolution.DAL.PurchaseOrderHeader,Evolution.FilePackagerService.FilePackagerService.FileRecipient)~Evolution.DAL.FileTransferConfiguration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.moveFileToFTPFolder(System.String,System.String,System.String)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPurchaseOrder(Evolution.DAL.PurchaseOrderHeader,Evolution.DAL.FileTransferConfiguration,Evolution.FilePackagerService.FilePackagerService.FileRecipient)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.createPickDataFile(Evolution.DAL.SalesOrderHeader,System.Xml.Linq.XElement,System.String@)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getFileTransferConfiguration(Evolution.DAL.SalesOrderHeader)~Evolution.DAL.FileTransferConfiguration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPick(Evolution.DAL.SalesOrderHeader,Evolution.DAL.FileTransferConfiguration)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.createPickDataFile(Evolution.DAL.PickHeader,System.Xml.Linq.XElement,System.String@)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getFileTransferConfiguration(Evolution.DAL.PickHeader)~Evolution.DAL.FileTransferConfiguration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPick(Evolution.DAL.PickHeader,Evolution.DAL.FileTransferConfiguration)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPick(Evolution.Models.Models.PickHeaderModel,Evolution.DAL.FileTransferConfiguration)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.getFileTransferConfigurationModel(Evolution.DAL.PurchaseOrderHeader,Evolution.FilePackagerService.FilePackagerService.FileRecipient)~Evolution.Models.Models.FileTransferConfigurationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPick(Evolution.Models.Models.PickHeaderModel,Evolution.Models.Models.FileTransferConfigurationModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.FilePackagerService.FilePackagerService.processPurchaseOrder(Evolution.DAL.PurchaseOrderHeader,Evolution.Models.Models.FileTransferConfigurationModel,Evolution.FilePackagerService.FilePackagerService.FileRecipient)~Evolution.Models.Models.Error")]