
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.mapToModel(Evolution.DAL.Task)~Evolution.Models.Models.TaskModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,Evolution.Enumerations.TaskType,Evolution.Enumerations.TaskStatus,System.Nullable{System.Int32},System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Nullable{Evolution.Enumerations.TaskType},System.Nullable{Evolution.Enumerations.TaskStatus},System.Nullable{System.Int32},System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Nullable{System.Int32},System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.validateTaskModel(Evolution.Models.Models.TaskModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Boolean)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Boolean)~Evolution.Models.Models.TaskListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.TaskManagerService.TaskManagerService.FindTaskListModel(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Boolean)~Evolution.Models.Models.TaskListModel")]