
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.Note)~Evolution.Models.Models.NoteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.validateNoteModel(Evolution.Models.Models.NoteModel)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.FindNotesListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.NoteListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.FindNotesListModel(Evolution.Enumerations.NoteType,System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.NoteListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.NoteAttachment)~Evolution.Models.Models.NoteAttachmentModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.FindNotesListModel(Evolution.Enumerations.NoteType,System.Int32,System.Int32,System.Int32,System.Int32,System.String,Evolution.Enumerations.MediaSize)~Evolution.Models.Models.NoteListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.Note,Evolution.Enumerations.MediaSize)~Evolution.Models.Models.NoteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.NoteAttachment,Evolution.Enumerations.MediaSize)~Evolution.Models.Models.NoteAttachmentModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.FindNotesListModel(Evolution.Enumerations.NoteType,System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Int32,System.Int32)~Evolution.Models.Models.NoteListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.Note,System.Int32,System.Int32)~Evolution.Models.Models.NoteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.NoteAttachment,System.Int32,System.Int32)~Evolution.Models.Models.NoteAttachmentModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.FindNotesListModel(Evolution.Enumerations.NoteType,System.Int32,System.Int32,System.Int32,System.Int32,System.String,Evolution.Enumerations.MediaSize,System.Int32,System.Int32)~Evolution.Models.Models.NoteListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.Note,Evolution.Enumerations.MediaSize,System.Int32,System.Int32)~Evolution.Models.Models.NoteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.mapToModel(Evolution.DAL.NoteAttachment,Evolution.Enumerations.MediaSize,System.Int32,System.Int32)~Evolution.Models.Models.NoteAttachmentModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NoteService.NoteService.validateNoteModel(Evolution.Models.Models.NoteModel)~Evolution.Models.Models.Error")]