
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.FindBrandListModel(System.Int32,System.Int32,System.Int32,System.String,System.Boolean)~Evolution.Models.Models.BrandListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.validateModel(Evolution.Models.Models.BrandModel)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.FindBrandCategoriesListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.BrandCategoryListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.validateModel(Evolution.Models.Models.BrandCategoryModel)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getProperties(Evolution.DAL.Product)~System.Collections.Generic.List{Evolution.Models.Models.PropertyItemModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.logChanges(Evolution.DAL.Product,Evolution.DAL.Product,Evolution.Models.Models.UserModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.mapToModel(Evolution.DAL.ProductLocation)~Evolution.Models.Models.ProductLocationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getField(Evolution.DAL.FileImportRow,System.String)~Evolution.DAL.FileImportField")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.validateModel(Evolution.Models.Models.ProductMediaModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.validateModel(Evolution.Models.Models.BrandModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getProperties(Product)~System.Collections.Generic.List{Evolution.Models.Models.PropertyItemModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.logChanges(Product,Product,Evolution.Models.Models.UserModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getProperties(Product)~System.Collections.Generic.List{Evolution.Models.Models.PropertyItemModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.logChanges(Product,Product,Evolution.Models.Models.UserModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getProperties(Product)~System.Collections.Generic.List{Evolution.Models.Models.PropertyItemModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.logChanges(Product,Product,Evolution.Models.Models.UserModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.getProperties(Product)~System.Collections.Generic.List{Evolution.Models.Models.PropertyItemModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.logChanges(Product,Product,Evolution.Models.Models.UserModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.validateModel(Evolution.Models.Models.BrandCategoryModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.FindProductComplianceListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.ProductComplianceListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.mapToModel(Evolution.DAL.ProductCompliance)~Evolution.Models.Models.ProductComplianceModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.deleteProductComplianceAttachment(System.Int32)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ProductService.ProductService.FindProductComplianceListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.String,Evolution.Enumerations.SortOrder)~Evolution.Models.Models.ProductComplianceListModel")]