
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.FindShipmentsListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.ShipmentListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.validateShipmentModel(Evolution.Models.Models.ShipmentModel)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.mapToEntity(Evolution.Models.Models.ShipmentModel,Evolution.DAL.Shipment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.FindShipmentsListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String)~Evolution.Models.Models.ShipmentListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.FindShipmentsListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Nullable{System.Int32},System.Nullable{System.Int32},System.Nullable{System.Int32})~Evolution.Models.Models.ShipmentResultListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.mapToEntity(Evolution.Models.Models.ShipmentContentModel,Evolution.DAL.ShipmentContent)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.validateShipmentContentModel(Evolution.Models.Models.ShipmentContentModel)~Evolution.Models.Models.ModelError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.FindShipmentsListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Int32,System.Int32,System.Int32)~Evolution.Models.Models.ShipmentResultListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.FindShipmentsListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.Int32,System.Int32,System.Int32,System.String,Evolution.Enumerations.SortOrder)~Evolution.Models.Models.ShipmentResultListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.validateShipmentModel(Evolution.Models.Models.ShipmentModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.ShipmentService.ShipmentService.validateShipmentContentModel(Evolution.Models.Models.ShipmentContentModel)~Evolution.Models.Models.Error")]