
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{Evolution.DAL.EMailQueue},System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(System.String)~System.Collections.Generic.List{Evolution.DAL.EMailQueue}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{Evolution.DAL.EMailQueue},Evolution.Models.Models.UserModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(Evolution.Models.Models.UserModel)~System.Collections.Generic.List{Evolution.DAL.EMailQueue}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{EMailQueue},Evolution.Models.Models.UserModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(Evolution.Models.Models.UserModel)~System.Collections.Generic.List{EMailQueue}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{EMailQueue},Evolution.Models.Models.UserModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(Evolution.Models.Models.UserModel)~System.Collections.Generic.List{EMailQueue}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{EMailQueue},Evolution.Models.Models.UserModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(Evolution.Models.Models.UserModel)~System.Collections.Generic.List{EMailQueue}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.checkEMailContent(System.Collections.Generic.List{EMailQueue},Evolution.Models.Models.UserModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.EMailServiceTests.EMailServiceTests.getMessages(Evolution.Models.Models.UserModel)~System.Collections.Generic.List{EMailQueue}")]