
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.mapToModel(Evolution.DAL.PickHeader,Evolution.Models.Models.PickHeaderModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.addPickDetails(Evolution.Models.Models.PickHeaderModel,System.Collections.Generic.List{Evolution.Models.Models.SalesOrderDetailModel})~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.createPick(Evolution.Models.Models.SalesOrderHeaderModel,Evolution.Models.Models.PickHeaderModel@)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.createPickDataFile(Evolution.Models.Models.PickHeaderModel)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.mapToModel(Evolution.DAL.PickDetail)~Evolution.Models.Models.PickDetailModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.createPickDataFile(Evolution.Models.Models.PickHeaderModel,System.Xml.Linq.XElement,System.String@)~Evolution.Models.Models.Error")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.doReplacements(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.getFileTransferConfiguration(Evolution.Models.Models.PickHeaderModel)~Evolution.DAL.FileTransferConfiguration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.getTemplateFileName(Evolution.DAL.FileTransferConfiguration)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.FindPicksListModel(System.Int32,System.Int32,System.Int32,System.Int32,System.String,System.String,Evolution.Enumerations.SortOrder)~Evolution.Models.Models.PicksListModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.mapToModel(Evolution.DAL.PickHeader)~Evolution.Models.Models.PickHeaderModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PickService.PickService.createPick(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.SalesOrderHeaderModel,Evolution.Models.Models.PickHeaderModel@)~Evolution.Models.Models.Error")]