[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NuOrderImportService.NuOrderImportService.GetCustomer(Evolution.Models.Models.CompanyModel,System.Collections.Generic.Dictionary{System.String,System.String})~Evolution.Models.Models.CustomerModel")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NuOrderImportService.NuOrderImportService.GetCustomer(Evolution.Models.Models.CompanyModel,System.Collections.Generic.Dictionary{System.String,System.String},Evolution.Models.Models.UserModel)~Evolution.Models.Models.CustomerModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NuOrderImportService.NuOrderImportService.MapFileToTemp(System.String,System.Collections.Generic.List{System.Collections.Generic.Dictionary{System.String,System.String}},Evolution.Models.Models.UserModel)~System.Collections.Generic.List{Evolution.DAL.NuOrderImportTemp}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NuOrderImportService.NuOrderImportService.MapTempToSalesDetails(System.Collections.Generic.List{Evolution.DAL.NuOrderImportTemp})~System.Collections.Generic.List{Evolution.DAL.SalesOrderDetail}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.NuOrderImportService.NuOrderImportService.MapTempToSalesHeader(System.Collections.Generic.List{Evolution.DAL.NuOrderImportTemp},System.String)~Evolution.DAL.SalesOrderHeader")]// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
