
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerAddress(System.Int32,System.Int32,Evolution.Models.Models.UserModel)~Evolution.Models.Models.CustomerAddressModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerConflict(System.Int32,System.Int32,Evolution.Models.Models.UserModel,System.Int32)~Evolution.Models.Models.CustomerConflictModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerMarketing(System.Int32,System.Int32,Evolution.Models.Models.UserModel,System.Int32)~Evolution.Models.Models.CustomerMarketingModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createBrandCategorySalesPerson(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.BrandCategoryModel,Evolution.Models.Models.CustomerModel,Evolution.Models.Models.UserModel,Evolution.Models.Models.LOVItemModel)~Evolution.Models.Models.BrandCategorySalesPersonModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.getSalesPersonType~Evolution.Models.Models.LOVItemModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.mapToModel(Evolution.DAL.BrandCategorySalesPerson)~Evolution.Models.Models.BrandCategorySalesPersonModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerContact(System.Int32,System.Int32,Evolution.Models.Models.UserModel)~Evolution.Models.Models.CustomerContactModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerFreight(System.Int32,System.Int32,Evolution.Models.Models.UserModel)~Evolution.Models.Models.CustomerFreightModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.addCreditCard(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.UserModel,Evolution.Models.Models.CustomerModel)~Evolution.Models.Models.CreditCardModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.FindCreditCardsListItemModelTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.FindCreditCardsListModelTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerAddress(System.Int32,System.Int32,Evolution.Models.Models.UserModel,Evolution.Enumerations.AddressType)~Evolution.Models.Models.CustomerAddressModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.checkDefaults(Evolution.Models.Models.CompanyModel,System.Nullable{System.Int32},System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.getCompany(System.String)~Evolution.Models.Models.CompanyModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerDefault(Evolution.Models.Models.CompanyModel)~Evolution.Models.Models.CustomerDefaultModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.addCreditCard(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.CustomerModel)~Evolution.Models.Models.CreditCardModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.FindBrandCategorySalesPersonsModelTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.getAdminPersonType~Evolution.Models.Models.LOVItemModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.CustomerServiceTests.CustomerServiceTests.createCustomerMarketing(System.Int32,System.Int32,Evolution.Models.Models.UserModel,Evolution.Models.Models.CustomerContactModel)~Evolution.Models.Models.CustomerMarketingModel")]