
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.GetCustomer(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionHeader)~Evolution.Models.Models.CustomerModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.MapFileImportDetailToTemp(System.String,Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionLine[],Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionHeader,Evolution.DAL.ScheduledTask)~System.Collections.Generic.List{Evolution.DAL.PepperiImportDetailTemp}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.MapTempToSalesDetail(System.Collections.Generic.ICollection{Evolution.DAL.PepperiImportDetailTemp},Evolution.DAL.ScheduledTask,Evolution.DAL.Customer)~System.Collections.Generic.List{Evolution.DAL.SalesOrderDetail}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.MapTempToSalesHeader(Evolution.DAL.PepperiImportHeaderTemp,Evolution.DAL.ScheduledTask,Evolution.DAL.Customer)~Evolution.DAL.SalesOrderHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.GetCustomer(Evolution.Models.Models.CompanyModel,Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionHeader,Evolution.Models.Models.UserModel)~Evolution.Models.Models.CustomerModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Evolution.PepperiImportService.PepperiImportService.MapFileImportDetailToTemp(System.String,Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionLine[],Evolution.Models.Models.PepperiTransactionTempModel.SalesTransactionTransactionHeader,Evolution.Models.Models.UserModel,Evolution.DAL.ScheduledTask)~System.Collections.Generic.List{Evolution.DAL.PepperiImportDetailTemp}")]